### ISSUE TITLE
Many tests are missing reference_output files

### ISSUE THREAD

**Issue by psteinfeld** [fujitsu/compiler-test-suite#7]
Here's the list:
0023_0000
0023_0001
0023_0002
0023_0003
0023_0004
0023_0005
0023_0006
0023_0007
0023_0008
0023_0009
0023_0010
0023_0011
0023_0012
0023_0013
0023_0014
0023_0015
0023_0016
0023_0018
0023_0019
0023_0020
0023_0021
0023_0022
0023_0023
0023_0024
0070_0016
0070_0024
0070_0186
0070_0187
0077_0014
0079_0009
0091_0054
0093_0000
0093_0001
0093_0002
0093_0003
0093_0004
0093_0005
0093_0006
0093_0007
0093_0008
0093_0009
0093_0010
0093_0011
0093_0012
0093_0013
0093_0014
0093_0015
0093_0016
0093_0017
0093_0018
0093_0019
0093_0020
0093_0021
0093_0022
0093_0023
0093_0024
0093_0025
0093_0026
0093_0027
0093_0028
0093_0029
0093_0030
0093_0031
0093_0032
0093_0033
0093_0034
0093_0035
0093_0036
0093_0037
0093_0038
0093_0039
0093_0040
0093_0041
0093_0042
0093_0043
0093_0044
0093_0045
0093_0046
0093_0047
0093_0048
0093_0049
0093_0050
0093_0051
0093_0052
0093_0053
0093_0054
0093_0055
0093_0056
0093_0057
0093_0058
0093_0059
0093_0060
0093_0061
0093_0062
0093_0063
0093_0064
0093_0065
0093_0066
0093_0067
0093_0068
0093_0069
0093_0070
0093_0071
0093_0072
0093_0073
0093_0074
0093_0075
0093_0076
0093_0077
0093_0078
0093_0079
0093_0080
0093_0081
0093_0082
0093_0083
0093_0084
0093_0085
0093_0086
0093_0087
0093_0088
0093_0089
0093_0090
0093_0091
0093_0092
0093_0093
0093_0094
0093_0095
0093_0096
0093_0097
0093_0098
0093_0099
0093_0100
0093_0101
0093_0102
0093_0103
0093_0104
0093_0105
0093_0106
0093_0107
0093_0108
0093_0109
0093_0110
0093_0111
0093_0112
0093_0113
0093_0114
0093_0115
0093_0116
0093_0117
0093_0118
0093_0119
0093_0120
0093_0121
0093_0122
0093_0123
0093_0124
0093_0125
0093_0126
0093_0127
0093_0128
0093_0129
0093_0130
0093_0131
0093_0132
0093_0133
0093_0134
0093_0135
0093_0136
0093_0137
0093_0138
0093_0139
0093_0140
0093_0141
0093_0142
0093_0143
0093_0144
0093_0145
0093_0146
0093_0147
0093_0148
0093_0149
0093_0150
0093_0151
0093_0152
0093_0153
0093_0154
0093_0155
0093_0156
0093_0157
0093_0158
0093_0159
0093_0160
0093_0161
0093_0162
0093_0163
0093_0164
0093_0165
0093_0166
0093_0167
0093_0168
0093_0169
0093_0170
0093_0171
0093_0172
0093_0173
0093_0174
0093_0175
0093_0176
0093_0177
0093_0178
0093_0179
0093_0180
0093_0181
0093_0182
0093_0183
0093_0184
0093_0185
0093_0186
0093_0187
0093_0188
0093_0189
0093_0190
0093_0191
0093_0192
0093_0193
0093_0194
0093_0195
0093_0196
0093_0197
0093_0198
0093_0199
0093_0200
0093_0201
0093_0202
0093_0203
0093_0204
0093_0205
0093_0206
0093_0207
0093_0208
0093_0209
0093_0210
0093_0211
0093_0212
0093_0213
0093_0214
0093_0215
0093_0216
0093_0217
0093_0218
0093_0219
0093_0220
0093_0221
0093_0222
0093_0223
0093_0224
0093_0225
0093_0226
0093_0227
0093_0228
0093_0229
0093_0230
0093_0231
0093_0232
0093_0233
0093_0234
0093_0235
0093_0236
0093_0237
0093_0238
0093_0239
0093_0240
0093_0241
0093_0242
0093_0243
0093_0244
0093_0245
0093_0246
0093_0247
0093_0248
0093_0249
0093_0250
0093_0251
0093_0252
0093_0253
0093_0254
0093_0255
0093_0256
0093_0257
0093_0258
0093_0259
0093_0260
0093_0261
0093_0262
0093_0263
0093_0264
0093_0265
0093_0266
0093_0267
0093_0268
0093_0269
0093_0270
0093_0271
0093_0272
0093_0273
0093_0274
0093_0275
0093_0276
0093_0277
0093_0278
0093_0279
0093_0280
0093_0281
0093_0282
0093_0283
0093_0284
0093_0285
0093_0286
0093_0287
0093_0288
0093_0289
0093_0290
0093_0291
0093_0292
0093_0293
0093_0294
0093_0295
0093_0296
0093_0297
0093_0298
0093_0299
0093_0300
0093_0301
0093_0302
0093_0303
0093_0304
0093_0305
0093_0306
0093_0307
0093_0308
0093_0309
0093_0310
0093_0311
0093_0312
0093_0313
0093_0314
0093_0315
0093_0316
0093_0317
0093_0318
0093_0319
0093_0320
0093_0321
0093_0322
0093_0323
0093_0324
0093_0326
0093_0327
0093_0328
0093_0329
0093_0330
0093_0331
0093_0332
0093_0333
0093_0334
0093_0335
0093_0336
0093_0337
0093_0338
0093_0339
0093_0340
0093_0341
0093_0342
0093_0343
0093_0344
0093_0345
0093_0346
0093_0347
0093_0348
0093_0349
0093_0350
0093_0351
0093_0352
0093_0353
0097_0002
0097_0081
0110_0000
0110_0001
0110_0019
0112_0009
0116_0020
0116_0021
0116_0022
0116_0023
0116_0255
0116_0256
0116_0306
0118_0112
0118_0113
0118_0114
0118_0186
0118_0199
0119_0032
0119_0033
0121_0186
0121_0187
0121_0190
0121_0191
0121_0192
0121_0193
0121_0194
0122_0000
0122_0001
0122_0059
0122_0060
0122_0061
0122_0065
0122_0066
0122_0067
0123_0000
0123_0026
0123_0034
0123_0086
0129_0058
0131_0010
0131_0038
0134_0183
0134_0233
0134_0242
0136_0017
0136_0018
0138_0013
0139_0023
0141_0001
0141_0002
0141_0023
0141_0025
0141_0027
0141_0029
0141_0039
0141_0040
0141_0064
0144_0169
0145_0010
0145_0011
0147_0000
0147_0001
0147_0002
0147_0003
0147_0004
0147_0005
0147_0006
0147_0007
0153_0001
0153_0011
0153_0174
0153_0223
0153_0260
0153_0261
0153_0281
0153_0283
0153_0284
0153_0285
0154_0001
0155_0003
0157_0000
0157_0001
0157_0002
0157_0003
0157_0004
0157_0005
0157_0007
0157_0008
0157_0009
0157_0010
0157_0011
0157_0012
0157_0013
0157_0014
0157_0015
0157_0016
0157_0017
0157_0018
0157_0019
0157_0020
0157_0021
0162_0022
0163_0000
0163_0003
0163_0005
0163_0006
0169_0008
0169_0081
0169_0082
0169_0087
0169_0088
0169_0089
0169_0105
0169_0106
0169_0110
0169_0111
0169_0112
0169_0115
0169_0140
0170_0000
0170_0001
0170_0002
0170_0003
0170_0004
0170_0005
0170_0006
0170_0008
0170_0009
0170_0010
0170_0011
0170_0012
0170_0013
0170_0014
0170_0015
0170_0016
0170_0017
0170_0018
0170_0019
0170_0020
0170_0021
0170_0022
0170_0023
0170_0024
0170_0025
0170_0026
0170_0027
0170_0028
0170_0029
0170_0030
0170_0031
0170_0032
0170_0033
0170_0034
0170_0035
0170_0036
0170_0037
0170_0038
0170_0039
0170_0040
0170_0041
0170_0042
0170_0043
0170_0044
0170_0045
0170_0046
0173_0078
0173_0079
0173_0096
0173_0097
0173_0098
0173_0100
0173_0114
0173_0115
0173_0116
0173_0124
0173_0125
0173_0126
0173_0131
0173_0153
0173_0154
0173_0155
0173_0156
0173_0157
0173_0158
0173_0288
0178_0000
0182_0040
0182_0041
0184_0016
0191_0020
0195_0011
0196_0001
0208_0025
0209_0001
0215_0004
0215_0005
0215_0006
0217_0004
0217_0005
0217_0006
0237_0039
0237_0043
0237_0045
0239_0005
0239_0006
0239_0011
0239_0014
0239_0037
0239_0041
0239_0042
0239_0103
0239_0121
0239_0129
0240_0343
0240_0456
0242_0028
0242_0029
0244_0066
0244_0114
0244_0115
0244_0116
0244_0119
0244_0173
0244_0178
0244_0179
0244_0237
0244_0238
0245_0035
0246_0028
0246_0071
0246_0075
0251_0070
0251_0079
0251_0080
0251_0081
0251_0082
0251_0083
0251_0084
0251_0085
0251_0087
0251_0088
0251_0091
0251_0092
0251_0093
0251_0095
0251_0096
0251_0097
0251_0098
0251_0099
0251_0103
0251_0104
0251_0107
0251_0108
0251_0109
0251_0110
0251_0111
0251_0112
0251_0113
0251_0114
0251_0115
0251_0121
0251_0124
0251_0125
0251_0131
0251_0167
0251_0168
0251_0169
0251_0170
0251_0171
0251_0180
0251_0182
0251_0183
0251_0187
0251_0188
0251_0270
0251_0272
0251_0280
0251_0281
0255_0022
0256_0044
0256_0052
0256_0059
0256_0064
0257_0011
0257_0013
0257_0018
0257_0019
0257_0020
0257_0032
0257_0054
0257_0055
0257_0056
0257_0057
0257_0058
0257_0059
0257_0060
0257_0061
0257_0063
0257_0082
0257_0083
0257_0084
0257_0085
0257_0086
0257_0087
0257_0088
0257_0101
0257_0135
0257_0145
0257_0196
0257_0198
0269_0034
0269_0035
0269_0041
0269_0042
0273_0136
0273_0148
0273_0185
0273_0201
0275_0017
0275_0023
0275_0024
0275_0030
0275_0042
0275_0049
0275_0055
0280_0025
0280_0026
0280_0048
0282_0283
0282_0284
0282_0291
0282_0349
0282_0350
0283_0448
0283_0592
0285_0008
0285_0050
0285_0052
0285_0053
0285_0092
0288_0100
0289_0014
0289_0015
0289_0070
0290_0009
0290_0032
0291_0006
0291_0062
0291_0132
0293_0017
0294_0109
0295_0042
0296_0000
0299_0039
0299_0054
0300_0043
0300_0070
0300_0073
0300_0075
0300_0078
0300_0080
0300_0111
0304_0038
0304_0046
0305_0029
0305_0042
0305_0044
0306_0008
0306_0010
0306_0026
0306_0032
0306_0033
0316_0186
0325_0017
0325_0018
0325_0019
0325_0020
0336_0144
0337_0017
0337_0021
0337_0022
0337_0024
0337_0027
0337_0028
0337_0041
0337_0055
0337_0058
0337_0059
0337_0060
0337_0068
0337_0070
0337_0083
0337_0105
0337_0107
0338_0047
0338_0077
0338_0085
0338_0086
0338_0095
0338_0113
0338_0118
0338_0221
0341_0286
0341_0288
0344_0303
0344_0304
0344_0839
0344_0842
0347_0006
0351_0107
0351_0109
0351_0111
0351_0470
0351_0471
0351_0472
0351_0528
0351_0529
0351_0530
0351_0531
0351_0532
0351_0533
0351_0534
0351_0535
0351_0536
0351_0537
0351_0538
0351_0539
0351_0540
0351_0541
0351_0542
0351_0543
0351_0544
0351_0545
0351_0546
0351_0547
0351_0548
0351_0549
0351_0550
0351_0551
0351_0568
0352_0001
0352_0066
0353_0000
0353_0001
0353_0002
0353_0003
0353_0004
0353_0005
0353_0015
0355_0001
0355_0115
0355_0116
0355_0117
0355_0118
0355_0119
0355_0120
0355_0121
0355_0122
0355_0123
0355_0124
0355_0125
0355_0126
0355_0161
0355_0162
0355_0173
0357_0065
0357_0066
0359_0005
0359_0006
0359_0007
0359_0008
0359_0017
0359_0018
0359_0019
0359_0020
0359_0030
0360_0093
0360_0097
0360_0098
0360_0252
0360_0264
0360_0277
0360_0279
0360_0292
0360_0293
0360_0294
0360_0295
0360_0296
0360_0535
0360_0536
0360_0537
0360_0538
0361_0005
0364_0000
0366_0002
0366_0003
0366_0005
0366_0006
0366_0013
0366_0026
0366_0027
0366_0029
0367_0000
0367_0001
0370_0017
0370_0019
0370_0021
0370_0022
0370_0023
0370_0024
0370_0025
0370_0051
0370_0052
0370_0053
0370_0054
0370_0055
0370_0056
0370_0066
0370_0118
0370_0252
0370_0269
0371_0000
0371_0001
0371_0002
0371_0003
0371_0004
0372_0001
0372_0002
0372_0003
0373_0027
0373_0253
0376_0004
0380_0002
0380_0003
0380_0004
0380_0006
0380_0012
0380_0013
0380_0015
0381_0019
0382_0011
0382_0014
0382_0017
0382_0019
0382_0020
0382_0021
0382_0022
0382_0023
0382_0024
0382_0025
0382_0026
0382_0027
0382_0028
0382_0029
0382_0030
0384_0006
0390_0087
0390_0088
0390_0099
0390_0100
0390_0173
0390_0234
0390_0293
0390_0294
0390_0316
0390_0317
0390_0318
0390_0319
0390_0320
0390_0321
0390_0322
0390_0323
0390_0324
0390_0325
0390_0326
0390_0327
0390_0328
0390_0329
0390_0330
0390_0331
0390_0332
0390_0333
0390_0334
0390_0335
0390_0336
0390_0337
0390_0338
0390_0339
0390_0340
0390_0341
0390_0342
0390_0343
0390_0344
0390_0345
0390_0346
0390_0347
0390_0348
0390_0349
0390_0350
0390_0351
0390_0352
0390_0353
0390_0354
0390_0355
0390_0356
0390_0357
0390_0358
0390_0359
0390_0360
0390_0361
0390_0362
0390_0363
0390_0364
0390_0365
0390_0366
0390_0367
0390_0368
0390_0369
0390_0370
0390_0371
0390_0372
0390_0373
0390_0374
0390_0375
0390_0376
0390_0377
0390_0378
0390_0379
0390_0380
0390_0381
0390_0382
0390_0383
0390_0384
0390_0385
0390_0386
0390_0387
0390_0388
0390_0389
0390_0390
0390_0391
0390_0392
0390_0393
0390_0394
0390_0395
0390_0396
0390_0397
0390_0398
0390_0399
0390_0400
0390_0401
0390_0402
0390_0403
0390_0404
0390_0405
0390_0406
0390_0407
0390_0408
0390_0409
0390_0410
0390_0411
0390_0412
0390_0413
0390_0414
0390_0415
0390_0416
0390_0417
0390_0418
0390_0419
0390_0420
0390_0421
0390_0422
0390_0423
0390_0424
0390_0425
0390_0426
0390_0427
0390_0428
0390_0429
0390_0430
0390_0431
0390_0432
0390_0433
0390_0434
0390_0435
0390_0436
0390_0437
0390_0438
0390_0439
0390_0440
0390_0441
0390_0442
0390_0443
0390_0444
0390_0445
0390_0446
0390_0447
0390_0448
0390_0449
0390_0450
0390_0451
0390_0452
0390_0453
0390_0454
0390_0455
0390_0456
0390_0457
0390_0458
0390_0459
0390_0460
0390_0461
0390_0462
0390_0463
0390_0464
0390_0465
0390_0466
0390_0467
0390_0468
0390_0469
0390_0470
0390_0471
0390_0472
0390_0473
0390_0474
0390_0475
0390_0476
0390_0477
0390_0478
0390_0479
0390_0480
0390_0481
0390_0482
0390_0483
0390_0484
0390_0485
0390_0486
0390_0487
0390_0488
0390_0489
0390_0490
0390_0491
0391_0008
0391_0009
0391_0025
0391_0026
0391_0027
0391_0029
0391_0030
0391_0031
0391_0032
0391_0043
0391_0053
0391_0056
0392_0014
0392_0015
0393_0019
0393_0034
0393_0038
0393_0084
0393_0085
0393_0139
0393_0140
0393_0177
0393_0180
0393_0183
0393_0186
0393_0189
0393_0192
0393_0258
0394_0012
0394_0013
0394_0019
0394_0020
0394_0021
0394_0022
0394_0023
0394_0024
0394_0025
0394_0026
0394_0027
0394_0028
0396_0001
0396_0002
0396_0003
0396_0004
0396_0005
0400_0005
0400_0011
0401_0063
0403_0009
0403_0010
0403_0011
0403_0012
0403_0013
0403_0016
0403_0018
0403_0019
0403_0020
0403_0021
0403_0022
0407_0001
0407_0002
0407_0003
0407_0004
0407_0009
0407_0015
0407_0016
0407_0017
0407_0018
0407_0019
0407_0020
0407_0022
0407_0023
0407_0024
0407_0025
0407_0026
0408_0001
0415_0009
0415_0017
0415_0019
0419_0038
0420_0049
0428_0019
0429_0002
0429_0008
0429_0009
0429_0014
0429_0019
0429_0020
0429_0035
0429_0036
0429_0048
0429_0049
0429_0066
0429_0067
0429_0105
0432_0014
0432_0025
0432_0026
0432_0027
0432_0028
0432_0029
0432_0030
0434_0005
0435_0045
0435_0046
0440_0007
0440_0008
0449_0006
0449_0007
0449_0013
0449_0017
0449_0018
0449_0033
0449_0036
0449_0037
0449_0038
0449_0039
0449_0044
0449_0045
0449_0046
0449_0049
0449_0053
0449_0054
0449_0055
0449_0059
0449_0060
0449_0074
0449_0075
0449_0082
0449_0084
0449_0085
0449_0087
0449_0088
0449_0089
0449_0090
0452_0000
0452_0001
0452_0002
0452_0003
0452_0004
0452_0008
0452_0009
0452_0022
0452_0026
0452_0027
0452_0031
0461_0007
0461_0012
0461_0021
0461_0024
0462_0007
0462_0009
0467_0000
0467_0001
0467_0002
0467_0003
0467_0005
0481_0045
0484_0000
0484_0001
0484_0003
0484_0004
0484_0006
0484_0007
0484_0011
0484_0012
0484_0013
0484_0014
0484_0015
0484_0016
0484_0017
0484_0018
0484_0019
0484_0020
0484_0022
0484_0023
0484_0024
0484_0025
0484_0027
0486_0078
0486_0122
0486_0125
0486_0190
0486_0271
0486_0273
0486_0289
0486_0290
0486_0297
0487_0078
0487_0086
0487_0087
0487_0144
0487_0152
0487_0159
0487_0161
0487_0173
0487_0210
0487_0234
0487_0256
0487_0262
0487_0264
0487_0266
0487_0300
0487_0311
0487_0313
0489_0001
0489_0002
0489_0003
0489_0007
0489_0008
0489_0017
0489_0030
0489_0031
0489_0081
0489_0082
0489_0083
0489_0084
0489_0085
0489_0088
0489_0097
0489_0123
0489_0129
0490_0002
0490_0005
0491_0004
0491_0005
0491_0009
0491_0054
0491_0056
0491_0088
0492_0003
0500_0010
0503_0005
0503_0018
0503_0025
0503_0030
0508_0004
0510_0002
0517_0008
0517_0017
0520_0000
0520_0001
0520_0002
0520_0003
0520_0004
0520_0005
0520_0006
0520_0007
0520_0008
0520_0009
0520_0010
0520_0011
0520_0012
0520_0013
0520_0014
0520_0015
0520_0016
0520_0017
0520_0018
0520_0019
0520_0020
0520_0021
0520_0022
0520_0023
0520_0024
0521_0012
0521_0013
0521_0014
0521_0015
0521_0016
0521_0017
0521_0018
0521_0019
0521_0020
0521_0021
0521_0022
0521_0034
0521_0035
0528_0083
0528_0084
0528_0085
0528_0086
0528_0088
0528_0107
0528_0108
0529_0004
0529_0005
0529_0006
0529_0007
0529_0008
0529_0013
0529_0018
0529_0019
0539_0003
0539_0004
0539_0005
0539_0012
0539_0052
0539_0053
0539_0057
0539_0058
0539_0059
0539_0060
0539_0061
0546_0000
0546_0001
0546_0003
0546_0012
0547_0004
0547_0051
0548_0008
0548_0043
0548_0044
0548_0067
0550_0002
0550_0006
0550_0015
0550_0031
0550_0034
0550_0044
0550_0071
0550_0073
0550_0074
0550_0075
0553_0015
0553_0016
0554_0100
0554_0102
0554_0103
0554_0110
0555_0032
0555_0067
0555_0079
0555_0161
0555_0163
0555_0166
0555_0171
0555_0172
0555_0173
0555_0175
0555_0180
0555_0181
0555_0182
0555_0183
0555_0187
0555_0188
0555_0189
0555_0190
0555_0191
0555_0196
0555_0197
0555_0198
0555_0199
0555_0200
0555_0205
0555_0206
0555_0207
0555_0208
0555_0210
0555_0211
0555_0212
0555_0214
0555_0217
0555_0222
0555_0223
0555_0224
0555_0225
0555_0229
0555_0230
0555_0231
0555_0232
0555_0233
0555_0234
0555_0235
0555_0236
0555_0237
0555_0238
0555_0239
0555_0240
0555_0241
0555_0242
0555_0244
0555_0245
0555_0299
0555_0302
0555_0427
0555_0580
0555_0581
0555_0595
0555_0709
0555_0742
0555_0795
0555_0809
0555_0812
0555_0813
0555_0842
0555_0846
0555_0849
0555_0851
0555_0858
0555_0860
0555_1096
0555_1098
0555_1099
0556_0024
0556_0069
0556_0070
0556_0072
0556_0079
0556_0127
0556_0135
0556_0137
0556_0138
0556_0139
0556_0140
0556_0175
0558_0140
0561_0000
0561_0020
0561_0021
0561_0022
0561_0023
0561_0024
0561_0039
0561_0046
0561_0049
0561_0050
0561_0051
0561_0054
0561_0067
0561_0086
0561_0137
0561_0157
0561_0158
0561_0159
0561_0160
0561_0161
0561_0163
0561_0164
0561_0165
0561_0166
0561_0168
0561_0170
0561_0171
0561_0173
0561_0184
0561_0186
0561_0187
0561_0188
0561_0189
0561_0190
0561_0191
0561_0201
0562_0079
0562_0080
0562_0081
0563_0047
0565_0005
0565_0011
0565_0020
0565_0024
0565_0038
0567_0017
0567_0021
0568_0002
0568_0011
0568_0012
0572_0049
0572_0089
0574_0003
0575_0000
0575_0001
0575_0002
0575_0003
0575_0004
0575_0005
0575_0006
0575_0007
0583_0027
0583_0028
0583_0029
0583_0030
0583_0031
0583_0032
0583_0033
0583_0035
0583_0036
0583_0037
0583_0038
0583_0039
0583_0040
0584_0039
0586_0152
0586_0159
0588_0018
0588_0037
0589_0011
0589_0042
0593_0000
0593_0002
0596_0009
0596_0010
0596_0015
0596_0018
0597_0002
0597_0004
0597_0005
0597_0006
0597_0010
0597_0011
0597_0013
0597_0014
0597_0015
0597_0016
0597_0017
0597_0018
0597_0019
0597_0020
0597_0021
0597_0022
0597_0023
0597_0024
0597_0025
0597_0026
0597_0027
0597_0028
0597_0030
0597_0031
0597_0032
0598_0000
0598_0001
0599_0000
0599_0001
0606_0035
0606_0058
0606_0132
0606_0136
0606_0148
0606_0149
0606_0176
0606_0177
0606_0178
0606_0186
0606_0187
0606_0188
0607_0056
0607_0058
0607_0059
0607_0060
0607_0061
0607_0063
0608_0012
0608_0014
0608_0015
0608_0017
0608_0019
0608_0020
0608_0022
0608_0024
0608_0025
0608_0026
0608_0027
0608_0029
0608_0032
0608_0034
0608_0036
0608_0043
0608_0044
0608_0045
0608_0046
0608_0047
0608_0048
0608_0054
0608_0058
0608_0059
0608_0060
0608_0061
0608_0063
0608_0065
0608_0066
0608_0070
0608_0071
0608_0072
0608_0086
0608_0124
0608_0125
0608_0126
0608_0129
0608_0131
0608_0132
0608_0133
0608_0134
0608_0135
0608_0136
0608_0137
0608_0138
0608_0139
0608_0140
0608_0141
0608_0143
0608_0144
0608_0145
0608_0146
0608_0166
0608_0167
0608_0168
0608_0171
0608_0174
0608_0176
0608_0180
0608_0185
0608_0201
0608_0203
0608_0206
0608_0210
0608_0212
0608_0214
0608_0215
0609_0001
0609_0003
0609_0006
0609_0008
0609_0013
0609_0014
0609_0015
0609_0016
0609_0041
0609_0042
0609_0043
0609_0044
0609_0045
0609_0046
0609_0047
0609_0058
0609_0059
0609_0063
0609_0066
0609_0073
0609_0074
0609_0075
0609_0076
0609_0079
0610_0029
0610_0080
0611_0004
0611_0005
0611_0006
0611_0007
0611_0008
0611_0014
0611_0015
0611_0016
0611_0017
0611_0018
0611_0024
0611_0025
0611_0026
0611_0027
0611_0028
0611_0033
0611_0034
0611_0035
0611_0039
0611_0040
0611_0048
0611_0049
0612_0021
0612_0022
0612_0023
0612_0024
0612_0025
0612_0026
0612_0027
0612_0028
0612_0029
0612_0030
0615_0000
0615_0001
0615_0002
0615_0003
0615_0004
0615_0005
0615_0006
0615_0007
0616_0016
0616_0017
0616_0018
0618_0014
0618_0015
0618_0016
0619_0017
0619_0018
0619_0019
0619_0175
0619_0270
0619_0286
0624_0042
0626_0020
0626_0037
0626_0038
0629_0030
0629_0047
0629_0187
0629_0188
0629_0201
0629_0322
0629_0472
0632_0015
0632_0020
0632_0021
0632_0022
0632_0023
0632_0024
0632_0025
0632_0026
0633_0004
0634_0047
0635_0157
0638_0047
0638_0051
0640_0014
0640_0022
0640_0038
0640_0088
0640_0089
0640_0209
0640_0216
0640_0218
0640_0219
0640_0231
0640_0324
0640_0327
0640_0344
0640_0345
0640_0346
0640_0378
0640_0421
0641_0297
0642_0028
0644_0037
0650_0012
0658_0027
0658_0028
0660_0022
0660_0024
0660_0026
0660_0028
0660_0029
0660_0031
0660_0033
0660_0039
0660_0041
0660_0044
0660_0047
0660_0048
0660_0049
0660_0050
0660_0051
0660_0052
0661_0003
0661_0004
0661_0011
0661_0022
0661_0028
0663_0000
0663_0001
0663_0002
0663_0003
0663_0004
0663_0005
0663_0006
0663_0007
0663_0008
0663_0009
0663_0010
0663_0011
0663_0012
0663_0013
0663_0014
0663_0015
0663_0016
0663_0017
0663_0018
0663_0019
0663_0020
0663_0021
0663_0022
0663_0023
0663_0024
0663_0025
0663_0026
0663_0027
0663_0028
0663_0029
0663_0030
0663_0031
0663_0032
0663_0033
0663_0034
0663_0035
0663_0036
0667_0009
0667_0010
0667_0011
0667_0012
0667_0013
0668_0096
0668_0200
0670_0003
0670_0004
0670_0005
0670_0015
0670_0016
0670_0018
0670_0026
0670_0029
0670_0040
0670_0041
0670_0046
0670_0050
0670_0076
0670_0077
0672_0004
0672_0005
0672_0006
0672_0007
0672_0008
0672_0009
0672_0010
0672_0011
0672_0012
0672_0013
0672_0019
0672_0020
0672_0021
0672_0024
0672_0025
0672_0026
0672_0027
0672_0028
0672_0029
0672_0030
0672_0031
0672_0032
0672_0033
0672_0034
0672_0035
0672_0036
0672_0037
0672_0038
0672_0051
0672_0070
0672_0071
0672_0072
0672_0073
0672_0074
0672_0075
0672_0076
0672_0077
0672_0078
0672_0079
0672_0080
0672_0081
0672_0082
0672_0083
0672_0084
0672_0085
0672_0086
0672_0087
0672_0088
0672_0089
0672_0090
0672_0091
0672_0092
0672_0093
0672_0094
0672_0095
0672_0096
0672_0097
0672_0098
0673_0007
0673_0023
0673_0026
0673_0029
0673_0030
0673_0032
0673_0044
0674_0041
0674_0042
0675_0057
0675_0058
0675_0059
0675_0060
0675_0086
0675_0087
0675_0088
0675_0093
0675_0136
0675_0137
0675_0138
0675_0142
0675_0143
0675_0167
0675_0168
0675_0169
0675_0170
0675_0176
0675_0208
0675_0210
0675_0211
0675_0212
0675_0213
0675_0214
0675_0215
0675_0216
0675_0217
0675_0219
0675_0221
0675_0276
0675_0277
0675_0278
0675_0290
0675_0291
0675_0306
0676_0193
0676_0204
0677_0067
0679_0058
0679_0295
0679_0402
0679_0496
0680_0119
0680_0120
0684_0006
0684_0031
0684_0049
0684_0052
0685_0001
0685_0002
0685_0003
0685_0010
0685_0011
0685_0012
0685_0014
0686_0009
0686_0012
0686_0013
0686_0014
0686_0015
0686_0017
0688_0012
0688_0046
0688_0050
0688_0053
0688_0054
0688_0058
0691_0041
0691_0042
0691_0045
0691_0088
0691_0091
0691_0092
0691_0099
0691_0103
0691_0104
0697_0017
0702_0018

**Comment by fj1nose** [comment]
@psteinfeld  Thank you very much for contacting us.I'm sorry for the late reply. 
Itis a specification.The README Current Status: Many missing reference output files (used to verify outputs from test programs).

**Comment by psteinfeld** [comment]
Thank you for looking at this.

But I'm not sure why you closed it.  This issue has a useful list of all of the tests that are missing output files.  I would think that this issue should remain open until either the missing output files are supplied or the tests are removed.

**Comment by kawashima-fj** [comment]
@psteinfeld Thanks for your interest to our test suite. Your feedback was very helpful. Let me explain the background of this issue. I'm a colleague of @fj1nose.

Many test are missing reference output files. There are two reasons.

1. Some tests can be compiled but cannot be executed or execution is meaningless. For example, there may be tests which assume a specific CPU (Arm optional features, SVE register size, ...). These tests are still useful to detect compilation errors.
2. Some tests result in FAIL but we have not yet investigated the cause (compiler bug or test bug). Not to confuse users of our test suite, they are set as compile-only. We will investigate the cause at some point. These tests are also still useful to detect compilation errors.

We'll consider updating the document to explain these.
