### ISSUE TITLE
Tests that are missing source files

### ISSUE THREAD

**Issue by psteinfeld** [fujitsu/compiler-test-suite#8]
Several tests are .reference_output files, but there's no source file:
0660_0023
0660_0025
0660_0027
0660_0030
0660_0032
0660_0034
0660_0040
0660_0042
0671_0000
0671_0001

The following tests have .input files but there's no source file:
0660/0660_0025
0660/0660_0027
0660/0660_0030
0660/0660_0032
0660/0660_0034
0660/0660_0040
0660/0660_0042
0660/0660_0045
0660/0660_0046
0660/snff90p40
0660/snff90p41
0660/snff90p42
0660/snff90p44
0660/snff90p45
0660/snff90p46
0660/snff90p52
0660/snff90p55
0660/snff90p571
0660/snff90p572

**Comment by fj1nose** [comment]
@psteinfeld  Thank you very much for contacting us. I'm sorry for the late reply.
Tests that are missing program source files are redundant.We remove those redundant files. We plan to fix it, by the end of December.
