### ISSUE TITLE
Tests that have reference input files but no reference output files

### ISSUE THREAD

**Issue by psteinfeld** [fujitsu/compiler-test-suite#9]
The following tests have source files and .reference_input files but no .reference_output files:
0337/0337_0021
0338/0338_0085
0338/0338_0086
0691/0691_0042
0691/0691_0099
0691/0691_0103
0691/0691_0104

**Comment by psteinfeld** [comment]
Thank you for looking at this.  Unfortunately, all of the tests listed in this issue are still missing reference output files.  Can you please fix this?

**Comment by kawashima-fj** [comment]
Why there are tests without reference output is explained in https://github.com/fujitsu/compiler-test-suite/issues/7#issuecomment-2561540567 . If these tests are inconvenient for you, please let us know the situation.
